#pragma once

#include <functional>
#include <memory>
#include <string>
#include <unordered_map>

#include <glm/vec2.hpp>

#include <Lucky/BatchRenderer.hpp>
#include <Lucky/Color.hpp>
#include <Lucky/Shader.hpp>
#include <Lucky/Texture.hpp>

struct hb_blob_t;
struct hb_face_t;
struct hb_font_t;
struct hb_buffer_t;

namespace Lucky {

struct GraphicsDevice;

struct TextEffect {
    float outlineThickness = 0; // screen pixels, 0 = no outline
    Color outlineColor = Color::Black;
    float glowThickness = 0; // how far the glow extends in screen pixels
    float glowSoftness = 0;  // width of glow falloff in screen pixels, 0 = no glow
    Color glowColor = Color::Black;
};

// MSDF font renderer using atlases generated by msdf-atlas-gen and HarfBuzz for text shaping.
//
// Atlas generation (with ligature glyphs):
//   msdf-atlas-gen -font <file.ttf> -type mtsdf -size <N> -pxrange <N>
//       -potr -yorigin top -charset <charset.txt>
//       -and -font <file.ttf> -glyphs "<glyph indices>"
//       -json <output.json> -imageout <output.png>
//
// The JSON and PNG must share the same base name and directory.
// The TTF file is needed separately for HarfBuzz text shaping.
class SdfFont {
  public:
    SdfFont(GraphicsDevice &graphicsDevice, const std::string &atlasJsonPath,
        const std::string &ttfPath);
    ~SdfFont();

    SdfFont(const SdfFont &) = delete;
    SdfFont &operator=(const SdfFont &) = delete;

    // Convenience: self-contained single draw call per string.
    void DrawString(BatchRenderer &batchRenderer, const std::string &text, glm::vec2 position,
        float fontSize, Color color, const TextEffect &effect = TextEffect{});

    // Path-following text assumes horizontal LTR scripts. Complex scripts (Arabic,
    // Devanagari, etc.) may need additional work for correct mark positioning.
    void DrawString(BatchRenderer &batchRenderer, const std::string &text,
        const std::function<glm::vec2(float)> &path, float fontSize, Color color,
        const TextEffect &effect = TextEffect{});

    // Batched: many strings in a single draw call. All strings share the same TextEffect.
    void BeginBatch(BatchRenderer &batchRenderer, const TextEffect &effect = TextEffect{});

    void DrawStringBatched(BatchRenderer &batchRenderer, const std::string &text,
        glm::vec2 position, float fontSize, Color color);

    // Path-following text assumes horizontal LTR scripts. Complex scripts (Arabic,
    // Devanagari, etc.) may need additional work for correct mark positioning.
    void DrawStringBatched(BatchRenderer &batchRenderer, const std::string &text,
        const std::function<glm::vec2(float)> &path, float fontSize, Color color);

    void EndBatch(BatchRenderer &batchRenderer);

    glm::vec2 MeasureString(const std::string &text, float fontSize);
    float GetLineHeight(float fontSize);
    float GetAscender(float fontSize);
    float GetDescender(float fontSize);

  private:
    struct GlyphData {
        float advance;
        float planeLeft, planeTop, planeRight, planeBottom;
        float atlasLeft, atlasTop, atlasRight, atlasBottom;
        bool hasGeometry;
    };

    static GlyphData ParseGlyphJson(const void *jsonValue);
    void ShapeText(const std::string &text);

    void EmitGlyphQuad(BatchRenderer &batchRenderer, const GlyphData &gd, float cursorX,
        float baselineY, float scale, const TextEffect &effect, Color color);

    std::unique_ptr<Texture> atlasTexture;
    std::unique_ptr<Shader> shader;
    std::unordered_map<uint32_t, GlyphData> glyphs; // keyed by glyph index

    // HarfBuzz
    hb_blob_t *hbBlob = nullptr;
    hb_face_t *hbFace = nullptr;
    hb_font_t *hbFont = nullptr;
    hb_buffer_t *hbBuffer = nullptr;

    // Cached for batched rendering (must outlive BeginBatch for uniform pointer)
    TextEffect batchEffect;
    struct MsdfParams {
        float pxRange;
        float atlasWidth;
        float atlasHeight;
        float outlineThickness;
        float outlineColorR, outlineColorG, outlineColorB, outlineColorA;
        float glowThickness;
        float glowSoftness;
        float pad0[2];
        float glowColorR, glowColorG, glowColorB, glowColorA;
    } batchParams;

    float lineHeight = 0;
    float ascender = 0;
    float descender = 0;
    float pxRange = 0;
    float atlasWidth = 0;
    float atlasHeight = 0;
    int upem = 0;
};

} // namespace Lucky
