#define STB_IMAGE_IMPLEMENTATION
#include <stb_image.h>
#define DR_WAV_IMPLEMENTATION
#include <dr_wav.h>
#define DR_MP3_IMPLEMENTATION
#include <dr_mp3.h>
#include <stb_vorbis.c>
#define CGLTF_IMPLEMENTATION
#include <cgltf.h>
